# =============================================================================
# GALANTIC VPC DEFINITION
# =============================================================================
apiVersion: galactic.datumapis.com/v1alpha
kind: VPC
metadata:
  name: galactic-prod-vpc
spec:
  networks:
    - 10.1.0.0/16
    - 2001:db8:beef::/48
---
# =============================================================================
# SJC REGION ATTACHMENT (San Jose)
# =============================================================================
apiVersion: galactic.datumapis.com/v1alpha
kind: VPCAttachment
metadata:
  name: vpc-attach-sjc
spec:
  vpc:
    apiVersion: galactic.datumapis.com/v1alpha
    kind: VPC
    name: galactic-prod-vpc
    namespace: default
  interface:
    name: galactic0
    # MATCHED TO SCHEMA: A list of strings inside the interface block
    addresses: 
      - "10.1.1.100/24"
      - "2001:db8:beef:1::100/64"
  routes:
    - { destination: 10.1.2.0/24, via: 10.1.1.3 }
---
# =============================================================================
# AMS REGION ATTACHMENT (Amsterdam)
# =============================================================================
apiVersion: galactic.datumapis.com/v1alpha
kind: VPCAttachment
metadata:
  name: vpc-attach-ams
spec:
  vpc:
    apiVersion: galactic.datumapis.com/v1alpha
    kind: VPC
    name: galactic-prod-vpc
    namespace: default
  interface:
    name: galactic0
    addresses: 
      - "10.1.2.100/24"
      - "2001:db8:beef:2::100/64"
---
# =============================================================================
# TEST POD IN SAN JOSE (SJC)
# =============================================================================
apiVersion: v1
kind: Pod
metadata:
  name: galantic-workload-sjc
  annotations:
    k8s.v1alpha.galactic.datumapis.com/vpc-attachment: vpc-attach-sjc
spec:
  nodeSelector:
    topology.kubernetes.io/region: sjc
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
