// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: local.proto

package local

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           string                 `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Vpcattachment string                 `protobuf:"bytes,2,opt,name=vpcattachment,proto3" json:"vpcattachment,omitempty"`
	Networks      []string               `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetVpc() string {
	if x != nil {
		return x.Vpc
	}
	return ""
}

func (x *RegisterRequest) GetVpcattachment() string {
	if x != nil {
		return x.Vpcattachment
	}
	return ""
}

func (x *RegisterRequest) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           string                 `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Vpcattachment string                 `protobuf:"bytes,2,opt,name=vpcattachment,proto3" json:"vpcattachment,omitempty"`
	Networks      []string               `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_local_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetVpc() string {
	if x != nil {
		return x.Vpc
	}
	return ""
}

func (x *DeregisterRequest) GetVpcattachment() string {
	if x != nil {
		return x.Vpcattachment
	}
	return ""
}

func (x *DeregisterRequest) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type DeregisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterReply) Reset() {
	*x = DeregisterReply{}
	mi := &file_local_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterReply) ProtoMessage() {}

func (x *DeregisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterReply.ProtoReflect.Descriptor instead.
func (*DeregisterReply) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterReply) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_local_proto protoreflect.FileDescriptor

const file_local_proto_rawDesc = "" +
	"\n" +
	"\vlocal.proto\x12\blocal.v1\"e\n" +
	"\x0fRegisterRequest\x12\x10\n" +
	"\x03vpc\x18\x01 \x01(\tR\x03vpc\x12$\n" +
	"\rvpcattachment\x18\x02 \x01(\tR\rvpcattachment\x12\x1a\n" +
	"\bnetworks\x18\x03 \x03(\tR\bnetworks\"-\n" +
	"\rRegisterReply\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\"g\n" +
	"\x11DeregisterRequest\x12\x10\n" +
	"\x03vpc\x18\x01 \x01(\tR\x03vpc\x12$\n" +
	"\rvpcattachment\x18\x02 \x01(\tR\rvpcattachment\x12\x1a\n" +
	"\bnetworks\x18\x03 \x03(\tR\bnetworks\"/\n" +
	"\x0fDeregisterReply\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed2\x8d\x01\n" +
	"\x05Local\x12>\n" +
	"\bRegister\x12\x19.local.v1.RegisterRequest\x1a\x17.local.v1.RegisterReply\x12D\n" +
	"\n" +
	"Deregister\x12\x1b.local.v1.DeregisterRequest\x1a\x19.local.v1.DeregisterReplyB7Z5github.com/datum-cloud/galactic-agent/api/local;localb\x06proto3"

var (
	file_local_proto_rawDescOnce sync.Once
	file_local_proto_rawDescData []byte
)

func file_local_proto_rawDescGZIP() []byte {
	file_local_proto_rawDescOnce.Do(func() {
		file_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_local_proto_rawDesc), len(file_local_proto_rawDesc)))
	})
	return file_local_proto_rawDescData
}

var file_local_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_local_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: local.v1.RegisterRequest
	(*RegisterReply)(nil),     // 1: local.v1.RegisterReply
	(*DeregisterRequest)(nil), // 2: local.v1.DeregisterRequest
	(*DeregisterReply)(nil),   // 3: local.v1.DeregisterReply
}
var file_local_proto_depIdxs = []int32{
	0, // 0: local.v1.Local.Register:input_type -> local.v1.RegisterRequest
	2, // 1: local.v1.Local.Deregister:input_type -> local.v1.DeregisterRequest
	1, // 2: local.v1.Local.Register:output_type -> local.v1.RegisterReply
	3, // 3: local.v1.Local.Deregister:output_type -> local.v1.DeregisterReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_local_proto_init() }
func file_local_proto_init() {
	if File_local_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_local_proto_rawDesc), len(file_local_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_local_proto_goTypes,
		DependencyIndexes: file_local_proto_depIdxs,
		MessageInfos:      file_local_proto_msgTypes,
	}.Build()
	File_local_proto = out.File
	file_local_proto_goTypes = nil
	file_local_proto_depIdxs = nil
}
